/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Sentiment {
    sentimentType: Variant_negative_positive_neutral;
    explanation: string;
}
export interface ChatbotResponse {
    marketingTips: string;
    explanation: string;
    practicalSteps: string;
}
export interface MarketingContent {
    advertisementCopy: string;
    productDescription: string;
    instagramCaptions: Array<string>;
}
export interface ColorPalette {
    colorMeanings: Array<string>;
    primaryColor: string;
    accentColor: string;
    secondaryColors: Array<string>;
}
export interface LogoConcept {
    iconConcept: string;
    fontStyle: string;
    primaryColor: string;
    backgroundStyle: string;
    secondaryColors: Array<string>;
    logoStyle: string;
}
export enum BrandTone {
    innovative = "innovative",
    playful = "playful",
    modern = "modern",
    trustworthy = "trustworthy",
    luxury = "luxury"
}
export enum Variant_negative_positive_neutral {
    negative = "negative",
    positive = "positive",
    neutral = "neutral"
}
export interface backendInterface {
    analyzeSentiment(_reviewText: string): Promise<Sentiment>;
    askChatbot(_question: string): Promise<ChatbotResponse>;
    generateBrandNames(_industry: string, _mainKeywords: string, _brandTone: BrandTone): Promise<Array<string>>;
    generateColorPalette(_industry: string, _brandTone: BrandTone): Promise<ColorPalette>;
    generateLogoConcept(_brandName: string, _industry: string, _brandTone: BrandTone): Promise<LogoConcept>;
    generateMarketingContent(_brandName: string, _productDescription: string, _targetAudience: string, _tone: BrandTone): Promise<MarketingContent>;
}
import type { BrandTone as _BrandTone, Sentiment as _Sentiment } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async analyzeSentiment(arg0: string): Promise<Sentiment> {
        if (this.processError) {
            try {
                const result = await this.actor.analyzeSentiment(arg0);
                return from_candid_Sentiment_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.analyzeSentiment(arg0);
            return from_candid_Sentiment_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async askChatbot(arg0: string): Promise<ChatbotResponse> {
        if (this.processError) {
            try {
                const result = await this.actor.askChatbot(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.askChatbot(arg0);
            return result;
        }
    }
    async generateBrandNames(arg0: string, arg1: string, arg2: BrandTone): Promise<Array<string>> {
        if (this.processError) {
            try {
                const result = await this.actor.generateBrandNames(arg0, arg1, to_candid_BrandTone_n4(this._uploadFile, this._downloadFile, arg2));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.generateBrandNames(arg0, arg1, to_candid_BrandTone_n4(this._uploadFile, this._downloadFile, arg2));
            return result;
        }
    }
    async generateColorPalette(arg0: string, arg1: BrandTone): Promise<ColorPalette> {
        if (this.processError) {
            try {
                const result = await this.actor.generateColorPalette(arg0, to_candid_BrandTone_n4(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.generateColorPalette(arg0, to_candid_BrandTone_n4(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async generateLogoConcept(arg0: string, arg1: string, arg2: BrandTone): Promise<LogoConcept> {
        if (this.processError) {
            try {
                const result = await this.actor.generateLogoConcept(arg0, arg1, to_candid_BrandTone_n4(this._uploadFile, this._downloadFile, arg2));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.generateLogoConcept(arg0, arg1, to_candid_BrandTone_n4(this._uploadFile, this._downloadFile, arg2));
            return result;
        }
    }
    async generateMarketingContent(arg0: string, arg1: string, arg2: string, arg3: BrandTone): Promise<MarketingContent> {
        if (this.processError) {
            try {
                const result = await this.actor.generateMarketingContent(arg0, arg1, arg2, to_candid_BrandTone_n4(this._uploadFile, this._downloadFile, arg3));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.generateMarketingContent(arg0, arg1, arg2, to_candid_BrandTone_n4(this._uploadFile, this._downloadFile, arg3));
            return result;
        }
    }
}
function from_candid_Sentiment_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Sentiment): Sentiment {
    return from_candid_record_n2(_uploadFile, _downloadFile, value);
}
function from_candid_record_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    sentimentType: {
        negative: null;
    } | {
        positive: null;
    } | {
        neutral: null;
    };
    explanation: string;
}): {
    sentimentType: Variant_negative_positive_neutral;
    explanation: string;
} {
    return {
        sentimentType: from_candid_variant_n3(_uploadFile, _downloadFile, value.sentimentType),
        explanation: value.explanation
    };
}
function from_candid_variant_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    negative: null;
} | {
    positive: null;
} | {
    neutral: null;
}): Variant_negative_positive_neutral {
    return "negative" in value ? Variant_negative_positive_neutral.negative : "positive" in value ? Variant_negative_positive_neutral.positive : "neutral" in value ? Variant_negative_positive_neutral.neutral : value;
}
function to_candid_BrandTone_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BrandTone): _BrandTone {
    return to_candid_variant_n5(_uploadFile, _downloadFile, value);
}
function to_candid_variant_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BrandTone): {
    innovative: null;
} | {
    playful: null;
} | {
    modern: null;
} | {
    trustworthy: null;
} | {
    luxury: null;
} {
    return value == BrandTone.innovative ? {
        innovative: null
    } : value == BrandTone.playful ? {
        playful: null
    } : value == BrandTone.modern ? {
        modern: null
    } : value == BrandTone.trustworthy ? {
        trustworthy: null
    } : value == BrandTone.luxury ? {
        luxury: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
