/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type BrandTone = { 'innovative' : null } |
  { 'playful' : null } |
  { 'modern' : null } |
  { 'trustworthy' : null } |
  { 'luxury' : null };
export interface ChatbotResponse {
  'marketingTips' : string,
  'explanation' : string,
  'practicalSteps' : string,
}
export interface ColorPalette {
  'colorMeanings' : Array<string>,
  'primaryColor' : string,
  'accentColor' : string,
  'secondaryColors' : Array<string>,
}
export interface LogoConcept {
  'iconConcept' : string,
  'fontStyle' : string,
  'primaryColor' : string,
  'backgroundStyle' : string,
  'secondaryColors' : Array<string>,
  'logoStyle' : string,
}
export interface MarketingContent {
  'advertisementCopy' : string,
  'productDescription' : string,
  'instagramCaptions' : Array<string>,
}
export interface Sentiment {
  'sentimentType' : { 'negative' : null } |
    { 'positive' : null } |
    { 'neutral' : null },
  'explanation' : string,
}
export interface _SERVICE {
  'analyzeSentiment' : ActorMethod<[string], Sentiment>,
  'askChatbot' : ActorMethod<[string], ChatbotResponse>,
  'generateBrandNames' : ActorMethod<
    [string, string, BrandTone],
    Array<string>
  >,
  'generateColorPalette' : ActorMethod<[string, BrandTone], ColorPalette>,
  'generateLogoConcept' : ActorMethod<[string, string, BrandTone], LogoConcept>,
  'generateMarketingContent' : ActorMethod<
    [string, string, string, BrandTone],
    MarketingContent
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];