/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Sentiment = IDL.Record({
  'sentimentType' : IDL.Variant({
    'negative' : IDL.Null,
    'positive' : IDL.Null,
    'neutral' : IDL.Null,
  }),
  'explanation' : IDL.Text,
});
export const ChatbotResponse = IDL.Record({
  'marketingTips' : IDL.Text,
  'explanation' : IDL.Text,
  'practicalSteps' : IDL.Text,
});
export const BrandTone = IDL.Variant({
  'innovative' : IDL.Null,
  'playful' : IDL.Null,
  'modern' : IDL.Null,
  'trustworthy' : IDL.Null,
  'luxury' : IDL.Null,
});
export const ColorPalette = IDL.Record({
  'colorMeanings' : IDL.Vec(IDL.Text),
  'primaryColor' : IDL.Text,
  'accentColor' : IDL.Text,
  'secondaryColors' : IDL.Vec(IDL.Text),
});
export const LogoConcept = IDL.Record({
  'iconConcept' : IDL.Text,
  'fontStyle' : IDL.Text,
  'primaryColor' : IDL.Text,
  'backgroundStyle' : IDL.Text,
  'secondaryColors' : IDL.Vec(IDL.Text),
  'logoStyle' : IDL.Text,
});
export const MarketingContent = IDL.Record({
  'advertisementCopy' : IDL.Text,
  'productDescription' : IDL.Text,
  'instagramCaptions' : IDL.Vec(IDL.Text),
});

export const idlService = IDL.Service({
  'analyzeSentiment' : IDL.Func([IDL.Text], [Sentiment], ['query']),
  'askChatbot' : IDL.Func([IDL.Text], [ChatbotResponse], ['query']),
  'generateBrandNames' : IDL.Func(
      [IDL.Text, IDL.Text, BrandTone],
      [IDL.Vec(IDL.Text)],
      ['query'],
    ),
  'generateColorPalette' : IDL.Func(
      [IDL.Text, BrandTone],
      [ColorPalette],
      ['query'],
    ),
  'generateLogoConcept' : IDL.Func(
      [IDL.Text, IDL.Text, BrandTone],
      [LogoConcept],
      ['query'],
    ),
  'generateMarketingContent' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, BrandTone],
      [MarketingContent],
      ['query'],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Sentiment = IDL.Record({
    'sentimentType' : IDL.Variant({
      'negative' : IDL.Null,
      'positive' : IDL.Null,
      'neutral' : IDL.Null,
    }),
    'explanation' : IDL.Text,
  });
  const ChatbotResponse = IDL.Record({
    'marketingTips' : IDL.Text,
    'explanation' : IDL.Text,
    'practicalSteps' : IDL.Text,
  });
  const BrandTone = IDL.Variant({
    'innovative' : IDL.Null,
    'playful' : IDL.Null,
    'modern' : IDL.Null,
    'trustworthy' : IDL.Null,
    'luxury' : IDL.Null,
  });
  const ColorPalette = IDL.Record({
    'colorMeanings' : IDL.Vec(IDL.Text),
    'primaryColor' : IDL.Text,
    'accentColor' : IDL.Text,
    'secondaryColors' : IDL.Vec(IDL.Text),
  });
  const LogoConcept = IDL.Record({
    'iconConcept' : IDL.Text,
    'fontStyle' : IDL.Text,
    'primaryColor' : IDL.Text,
    'backgroundStyle' : IDL.Text,
    'secondaryColors' : IDL.Vec(IDL.Text),
    'logoStyle' : IDL.Text,
  });
  const MarketingContent = IDL.Record({
    'advertisementCopy' : IDL.Text,
    'productDescription' : IDL.Text,
    'instagramCaptions' : IDL.Vec(IDL.Text),
  });
  
  return IDL.Service({
    'analyzeSentiment' : IDL.Func([IDL.Text], [Sentiment], ['query']),
    'askChatbot' : IDL.Func([IDL.Text], [ChatbotResponse], ['query']),
    'generateBrandNames' : IDL.Func(
        [IDL.Text, IDL.Text, BrandTone],
        [IDL.Vec(IDL.Text)],
        ['query'],
      ),
    'generateColorPalette' : IDL.Func(
        [IDL.Text, BrandTone],
        [ColorPalette],
        ['query'],
      ),
    'generateLogoConcept' : IDL.Func(
        [IDL.Text, IDL.Text, BrandTone],
        [LogoConcept],
        ['query'],
      ),
    'generateMarketingContent' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, BrandTone],
        [MarketingContent],
        ['query'],
      ),
  });
};

export const init = ({ IDL }) => { return []; };